// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Util from "@1r21/util";
import * as ApiH5 from "@1r21/api-h5";

function Detail(Props) {
  var id = Props.id;
  var match = React.useState(function () {
        return {
                id: "",
                title: "",
                cover: "",
                date: ""
              };
      });
  var setArticle = match[1];
  var article = match[0];
  var match$1 = React.useState(function () {
        return [];
      });
  var setTexts = match$1[1];
  React.useEffect((function () {
          ApiH5.getNewsById(id).then(function (ret) {
                setArticle(function (_p) {
                      return ret;
                    });
                var v = ret.transcript;
                if (v !== undefined) {
                  var formatTexts = Util.parseText(v);
                  setTexts(function (_p) {
                        return formatTexts;
                      });
                }
                return Promise.resolve(undefined);
              });
        }), [id]);
  var textContent = match$1[0].map(function (txt) {
        var style = {
          color: txt.style.color,
          fontWeight: txt.style.fontWeight
        };
        return React.createElement("p", {
                    key: txt.idx.toString(),
                    className: "my-2",
                    style: style
                  }, txt.value);
      });
  var href = article.source;
  var src = article.src;
  return React.createElement("div", {
              className: "w-3/5 mx-auto pb-[100px]"
            }, React.createElement("div", undefined, textContent, React.createElement("p", {
                      className: "text-right"
                    }, "from: ", href !== undefined ? React.createElement("a", {
                            className: "text-blue-500 italic underline",
                            href: href,
                            rel: "noreferrer",
                            target: "_blank"
                          }, "pbs") : "")), src !== undefined ? React.createElement("audio", {
                    className: "fixed bottom-2 w-3/5 outline-none",
                    controls: true,
                    src: src
                  }) : "");
}

var make = Detail;

export {
  make ,
}
/* react Not a pure module */
