// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Article from "./Article.mjs";
import * as ApiH5 from "@1r21/api-h5";

function Home(Props) {
  var match = React.useState(function () {
        return [];
      });
  var setArticles = match[1];
  React.useEffect((function () {
          ApiH5.getNews().then(function (ret) {
                setArticles(function (param) {
                      return ret.list;
                    });
                return Promise.resolve(undefined);
              });
        }), []);
  var articleContent = match[0].map(function (item) {
        return React.createElement("li", {
                    key: item.id,
                    className: "w-1/5 p-2"
                  }, React.createElement(Article.make, {
                        news: item
                      }));
      });
  return React.createElement("div", {
              className: "w-9/12 h-full mx-auto"
            }, React.createElement("ul", {
                  className: "flex flex-wrap"
                }, articleContent));
}

var make = Home;

export {
  make ,
}
/* react Not a pure module */
