// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import LoadingSvg from "../assets/loading.svg";

var loadingSvg = LoadingSvg;

function Loading(Props) {
  var style = {
    display: "flex",
    height: "400px"
  };
  return React.createElement("div", {
              style: style
            }, React.createElement("img", {
                  src: loadingSvg
                }));
}

var make = Loading;

export {
  loadingSvg ,
  make ,
}
/* loadingSvg Not a pure module */
