// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as LoadingSvgcomponent from "../assets/loading.svg?component";

var loadingSvg = LoadingSvgcomponent;

function Loading(Props) {
  var style = {
    display: "flex",
    height: "400px"
  };
  return React.createElement("div", {
              style: style
            }, React.createElement("loadingSvg", undefined));
}

var make = Loading;

export {
  loadingSvg ,
  make ,
}
/* loadingSvg Not a pure module */
