// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import LoadingSvgcomponent from "../assets/loading.svg?component";

var make = LoadingSvgcomponent;

var LoadingSvg = {
  make: make
};

function Loading(Props) {
  var delay = Props.delay;
  var match = React.useState(function () {
        return true;
      });
  var setDelay = match[1];
  React.useEffect((function () {
          setTimeout((function (param) {
                  setDelay(function (_p) {
                        return false;
                      });
                }), delay);
        }), []);
  var style = {
    display: "flex",
    height: "400px"
  };
  if (match[0]) {
    return null;
  } else {
    return React.createElement("div", {
                style: style
              }, React.createElement(make, {}));
  }
}

var make$1 = Loading;

export {
  LoadingSvg ,
  make$1 as make,
}
/* make Not a pure module */
