// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "./components/Home.mjs";
import * as React from "react";
import * as Detail from "./components/Detail.mjs";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.mjs";

function App(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (!match) {
    return React.createElement(Home.make, {});
  }
  if (match.hd !== "detail") {
    return null;
  }
  var match$1 = match.tl;
  if (match$1 && !match$1.tl) {
    return React.createElement(Detail.make, {
                id: match$1.hd
              });
  } else {
    return null;
  }
}

var make = App;

export {
  make ,
}
/* Home Not a pure module */
