// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.mjs";
import * as React from "react";
import * as WebVitals from "./WebVitals.mjs";
import * as ReactDom from "react-dom";

import './assets/index.css'
;

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(App.make, {}), root);
}

WebVitals.report(function (prim) {
      console.log(prim);
    });

export {
  
}
/*  Not a pure module */
