// Generated by ReScript, PLEASE EDIT WITH CARE

import * as WebVitals from "web-vitals";

function report(onPerfEntry) {
  WebVitals.getCLS(onPerfEntry);
  WebVitals.getFID(onPerfEntry);
  WebVitals.getFCP(onPerfEntry);
  WebVitals.getLCP(onPerfEntry);
  WebVitals.getTTFB(onPerfEntry);
}

export {
  report ,
}
/* web-vitals Not a pure module */
